#!/usr/bin/perl
#my ($comm,$host) = @ARGV;

$comm = $ARGV[0];
$host = $ARGV[1];
@result = `/usr/bin/snmpwalk -v 2c -c $comm $host .1.3.6.1.4.1.2620.1.5.6.0 2>&1`;
chomp @result;

 foreach(@result) {
   if (/SNMPv2-SMI(.*)\s=\sSTRING:\s\"active\"/) {
      $value = '1';
	  
   }
   
   if (/SNMPv2-SMI(.*)\s=\sSTRING:\s\"Not active\"/) {
      $value = '2';
	 
   }
   if (/SNMPv2-SMI(.*)\s=\sSTRING:\s\"standby\"/) {
      $value = '3';
	
   }
     print "$value\n";
     }
